cart/urls.py
from django.urls import path
from cart import views

app_name='cart'

urlpatterns=[
    path('cart_view', views.cart_view, name='cart_view'),
    path('add_cart/<int:p>', views.add_cart, name='add_cart'),
    path('minus/<int:p>', views.minus, name='minus'),
    path('delete/<int:p>', views.delete, name='delete'),
    path('order', views.order, name='order'),
    path('order_views', views.order_views, name='order_views'),
]

ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from search import views
app_name = 'search'
urlpatterns = [
    path('searchresult/',views.searchresult,name= "searchresult")
]

shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views

app_name='shop'
urlpatterns = [
    path('',views.category,name='category'),
    path('products/<slug:cslug>',views.products,name='products'),
    path('prodetail/<slug:pslug>',views.prodetail,name='prodetail'),
    path('register', views.register, name='register'),
    path('usersignin', views.usersignin, name='usersignin'),
    path('usersignout', views.usersignout, name='usersignout'),

]

cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User
# Create your models here.
class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    products=models.ForeignKey(Product,on_delete=models.CASCADE)
    date_added=models.DateField(auto_now_add=True)
    quantity=models.IntegerField(default=1)
    active=models.BooleanField(default=True)
    def subtotal(self):
        return self.quantity*self.products.price

    # category names setting
    def _str_(self):
        return self.products.name

class Account(models.Model):
    acc_number=models.CharField(max_length=200)
    acc_type=models.CharField(max_length=200)
    amount=models.IntegerField()
    def _str_(self):
        return self.acc_number

class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    products=models.ForeignKey(Product,on_delete=models.CASCADE)
    address=models.TextField()
    phone=models.CharField(max_length=100)
    order_status=models.CharField(max_length=30,default='Pending')
    delivery_status=models.CharField(max_length=30,default='Pending')
    no_ofitems=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)
    def _str_(self):
        return self.user.username

search/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render,redirect
from cart.models import Cart,Order,Account
from shop.models import Product
from django.contrib.auth.decorators import login_required


# Create your views here.
@login_required
def cart_view(request):
    total=0
    try:
        user=request.user
        cart=Cart.objects.filter(user=user)
        for i in cart:
            total+=i.quantity * i.products.price

    except Cart.DoesNotExist:
        pass
    return render(request,'cart.html',{'cart':cart,'total':total})

@login_required
def add_cart(request,p):
    product=Product.objects.get(id=p)
    user=request.user
    try:
        cart=Cart.objects.get(products=product,user=user)
        if cart.quantity<cart.products.stock:
            cart.quantity+=1
            cart.save()
    except:
        cart=Cart.objects.create(products=product,user=user,quantity=1) #main code
        cart.save()
    return redirect('cart:cart_view') #to go to verification

@login_required
def minus(request,p):
    product=Product.objects.get(id=p)
    user=request.user
    try:
        cart=Cart.objects.get(products=product,user=user)
        if cart.quantity>1:
            cart.quantity -= 1
            cart.save()
        else:
            cart.delete()
    except:
        pass
    return redirect('cart:cart_view') #to go to verification

@login_required
def delete(request,p):
    u=request.user
    p=Product.objects.get(id=p)
    try:
        cart=Cart.objects.get(products=p,user=u)
        cart.delete()
    except:
        pass
    return redirect('cart:cart_view')



@login_required
def order(request):
    total=0
    items=0
    if(request.method=='POST'):
        ad=request.POST['ad']
        ph=request.POST['ph']
        ac=request.POST['ac']
        user=request.user
        cart=Cart.objects.filter(user=user)
        for i in cart:
            total+=i.quantity * i.products.price
            items+=i.quantity
        ##amount verification
        account= Account.objects.get(acc_number=ac)
        if float(account.amount) >= total:
            account.amount=account.amount-total
            account.save()
            ## deleting from cart after placing order
            for i in cart:
                order=Order.objects.create(user=user,products=i.products,address=ad,phone=ph,
                                           order_status='Paid',no_ofitems=i.quantity)
                order.save()
            cart.delete()
            msg='Order placed successfully'
            return render(request,'confirmation.html')
            # return render(request, 'orderdetail.html', {'address': ad, 'phone': ph, 'account': ac,'total':total,'items': items})
        else:
            msg="Insufficient Amount, ypu cant place order."
            return render(request,'orderdetail.html',{"msg":msg})
    return render(request,'order.html')

@login_required
def order_views(request):
    user=request.user
    o=Order.objects.filter(user=user,order_status='Paid')
    return render(request,'orderview.html',{"o":o})

search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
# Create your views here.

def searchresult(request):
    products=None
    query= None
    if request.method == "POST":
        query=request.POST.get('q')
        if query:
            products=Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))
    return render(request,'search.html',{'query':query,'products':products})

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

</head>
<body>
<div class="container-fluid">
    <header>
    <center><img src="{% static 'img/banner.jpg' %}" height="100px" width="100px"></center>

        <nav class="navbar navbar-expand-lg navbar-light" style="background-color:rgb(160,168,173);">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link " aria-current="page" href="{% url 'shop:category'  %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Store
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="">All Categories</a></li>
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:prodetail' i.slug %}">{{i.name}}</a></li>
              {% endfor %}
          </ul>
        </li>

 {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link " href="{% url 'shop:usersignout' %}">LogOut</a>
        </li>
           <li class="nav-item">
            <a class="nav-link " href="{% url 'cart:cart_view' %}"><i class="fa-solid fa-cart-shopping"></i>{{item_count}}</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active text-primary" aria-current="page" href="{% url 'cart:order_views' %}">Your orders</a>
        </li>
{% else %}
         <li class="nav-item">
          <a class="nav-link " href="{% url 'shop:register' %}">Register</a>
         </li>
            <li class="nav-item">
          <a class="nav-link " href="{% url 'shop:usersignin' %}">Login</a>
         </li>
{% endif %}
           </ul>
      <form class="d-flex" action="{% url 'search:searchresult' %}" method="POST">
          {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success bg-primary" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
      </form>
    </div>
  </div>
</nav>    </header>

      {% block content %}
      {% endblock %}
      <footer>
        <div class="footer">
          <p><i class="fa-solid fa-copyright"></i>Myshop pvt ltd.All rights reserved.</p>
        </div>
      </footer>

</div>
</body>
</html>

templates/cart.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<div class="container-fluid" >
    {% if not cart %}
    <div>
        <h1 class="text-center">Cart is empty</h1>
    </div>
    <div>
        <strong><a href="{% url 'shop:category' %}">Continue shopping</a></strong>
    </div>
    {% else %}
    <div class="row-mx-auto">
        <div class="col-sm-8">
        <table class="table table-bordered border-dark">
        <tr>
            <th>Your items</th>
            <th>Product</th>
            <th>Product id</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total price</th>
        </tr>
            {% for i in cart %}
        <tr>
            <td><img src="{{i.products.image.url}}" style="height:200px; width:auto;"></td>
            <td>{{i.products.name}}</td>
            <td>{{i.products.id}}</td>
            <td>Unit price:{{i.products.price}}</td>
            <td>{{i.quantity}}</td>
<!--            <td>Total quantity:{{i.products.quantity}}*{{i.products.price}}</td>-->
            <td>{{i.subtotal}}</td>
            {% if i.quantity < i.products.stock %}
            <td>
                <a href="{% url 'cart:add_cart' i.products.id %}"><i class="fa fa-solid fa-plus-circle custom_icon" aria-hidden="true"></i></a>
                <a href="{% url 'cart:minus' i.products.id %}"><i class="fa fa-solid fa-minus-circle custom_icon" aria-hidden="true"></i></a>
                <a href="{% url 'cart:delete' i.products.id %}">🗑️<i class="fa-duotone fa-trash"></i></a>
            </td>
            {% else %}
            <a href="{% url 'cart:add_cart' i.products.id %}">add<i class="fa fa-solid fa-plus-circle custom_icon" aria-hidden="true"></i></a>
            <a href="{% url 'cart:minus' i.products.id %}">reduce<i class="fa fa-solid fa-minus-circle custom_icon" aria-hidden="true"></i></a>
            {% endif %}

            {% endfor %}
        </tr>
        </table>
        </div>

        <div class="col-sm-4"  style="margin-bottom:100px;">
            <table class="table table-bordered border-dark">
                <tr><th class="text-center">CHECKOUT</th></tr>
                <tr><th>Total price: ₹{{total}}</th></tr>
            </table>
            <a class="btn btn-primary center">Continue</a>
            <a class="btn btn-primary center" href="{% url 'cart:order' %}">Place order</a>
        </div>
    </div>
{% endif %}
</div>
{% endblock %}

templates/category.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<div>
    <img src="{% static 'img/banner.jpg'%}" style="width:100%; height:500px;">
</div>
<div>
    <!--    centered heading-->
    <center><h1 class="text-center">Our Products Range</h1>
        <!--    description-->
        <p class="text-justify">There are many4 variations of passages of Lorem Ipsum available,
            but the majority have suffered alteration in some form, by injected humour, or randomised
            words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum,
            you need to be sure there isn't anything embarrassing hidden in the middle of text.
            All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary,
            making this the first true generator on the Internet.</p>
    </center>

</div>
<!--    card display of 3 no.s-->
<div class="container" style="margin-bottom:100px;" >
<div class="row">
    {% for i in c %}
        <div class="col-sm-6">
           <div class="card" style="width: 18rem;">
                  <img src="{{i.image.url}}" class="card-img-top" style="height:300px; width:auto;"  alt="...">
                  <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-text">{{i.description}}</p>
                    <a href="{% url 'shop:products' i.slug %}" class="btn btn-primary">More Details</a>
                  </div>
           </div>
        </div>
    {% endfor %}
</div>
</div>
{% endblock %}

templates/confirmation.html
{% extends 'base.html' %}
{% load static%}
{% block content %}
<div>
  <h1 class="text-center">Your order placed successfully.</h1>
  <h1 class="text-center">Thank you.</h1>
  <a class="btn btn-danger" href="{% url 'shop:category' %}"></a>
</div>
{% endblock %}

templates/detail.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

<!--image-->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4 mt-3">
            <img src="{{p.image.url}}" style="height:300px; width:300px;" alt="{{p.image.url}}">
        </div>
        <div class="col-sm-8 mt-3 ">
            <h2>{{p.name}}</h2>
            <h3>₹ {{p.price}}</h3>
            <p>{{p.description}}</p>
<!--stock-->
            {% if p.stock <= 0 %}
            <h2>OUT OF STOCK</h2>
            {% else %}
            <a href="{% url 'cart:add_cart' p.id %}" class="btn btn-primary">Add to cart</a>
            {% endif %}
        </div>
    </div>
</div>


{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--Student details display-->
<h1>Login </h1>
<form method="POST">
  {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">User Name</label>
    <input type="text" class="form-control" name="u"  placeholder="enter user name">

  </div>


    <div class="mb-3">
    <label class="form-label">Password</label>
    <input type="password" class="form-control" name="p"  placeholder="enter your password">

  </div>
    <button type="submit" class="btn btn-primary">Submit</button>


  {% if messages %}
  {% for i in messages %}
  <ul class="messages">
    <li>{{i}}</li>
  </ul>
  {% endfor %}
  {% endif %}
  {% endblock %}

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/order.html
{% extends 'base.html' %}
{% load static%}
{% block content %}
<div class="container">
  <form method="POST">
      {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Address</label>
      <textarea type="text" class="form-control" name="ad" ></textarea>
    <div class="form-text"></div>
  </div>
  <div class="mb-3">
    <label class="form-label">Phone number</label>
    <input type="text" class="form-control" name="ph" >
    <div class="form-text"></div>
  </div>
   <div class="mb-3">
    <label class="form-label">Account number</label>
    <input type="text" class="form-control" name="ac">
    <div class="form-text"></div>
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
{% endblock %}

<!--address-->
<!--ph-->
<!--acc no-->

templates/orderdetail.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<div class="container">
    {{msg}}
    {{total}}
    {{items}}
</div>

{% endblock %}

templates/orderview.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<div class="container">
    <table class="table table-bordered border-dark">
        <h1 class="text-center">Order</h1>
        {% for i in o %}
        <tr>
            <th class="inv">Name of customer : {{user}}</th>
            <th class="inv"> <img src="{{i.products.image.url}}" style="height:100px; width:100px;"> </th>
<!--            <th class="inv">Account number : {{i.account}}</th>-->
            <th class="inv">Phone : {{i.phone}}</th>
            <th class="inv">Address : {{i.address}}</th>
<!--            <th class="inv">Products : {{i.items}}</th>-->
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

templates/product.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
<div>
    <img src="{% static 'img/banner1.jpg'%}" style="width:100%; height:500px;">
</div>


<div class="container-fluid">
    <!--    centered heading-->

    <center><h1 class="text-center" style="font-family:arial;">Product category: {{i.category.name}}</h1>
        <!--    description-->
        <p class="text-justify">There are many variations of passages of Lorem Ipsum available,
            but the majority have suffered alteration in some form, by injected humour, or randomised
            words which don't look even slightly believable. </p>
    </center>

</div>
<!--    category card display -->
<div class="container" style="margin-bottom:100px;" >
<div class="row mx-auto">
{% for i in c %}
    <div class="col-sm-3">
        <div class="card" style="width:20rem;">
  <img src="{{i.image.url}}" class="card-img-top"  style="height:200px; width:auto;"  alt="...">
  <div class="card-body">
    <h5 class="card-title" style="font-weight:bold; ">{{i.name}}</h5>
    <p class="card-text">{{i.description}}</p>
    <a href="{% url 'shop:prodetail' i.slug %}" class="btn btn-primary">Details</a>
  </div>
        </div>
    </div>


    {% endfor %}




</div>
</div>


{% endblock %}

templates/search.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

<center>
    <div>
        <h3> You have searched for {{query}}</h3>
    </div>
</center>
<div class="container" style="margin-bottom:100px;">
<div class="row mx-auto">
{% for i in products %}
    <div class="col-sm-4">
        <div class="card" style="width: 20rem;">
  <img src="{{i.image.url}}" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title" style="font-weight:bold; ">{{i.name}}</h5>
    <p class="card-text">{{i.description}}</p>
    <a href="{% url 'shop:prodetail' i.slug %}" class="btn btn-primary">Details</a>
  </div>
        </div>
    </div>
    {% empty %}
    <div>
        <h1> ZERO RESULT FOUND</h1>
    </div>



    {% endfor %}




</div>
</div>




{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--Student details display-->
<h1>Sign Up</h1>
<form method="POST" style="margin-bottom:100px;">
  {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">User Name</label>
    <input type="text" class="form-control" name="u"  placeholder="enter user name">

  </div>
     <div class="mb-3">
    <label class="form-label">First name </label>
    <input type="text" class="form-control" name="f" placeholder="enter first name " >

  </div>

  <div class="mb-3">
    <label class="form-label">Last name</label>
    <input type="text" class="form-control" name="l" placeholder="enter last name " >

  </div>

  <div class="mb-3">
    <label class="form-label">Email</label>
    <input type="email" class="form-control" name="e"  placeholder="enter email" >

  </div>

    <div class="mb-3">
    <label class="form-label">Password</label>
    <input type="password" class="form-control" name="p"  placeholder="enter your password">

  </div>

    <div class="mb-3">
    <label class="form-label">Confirm Password</label>
    <input type="password" class="form-control" name="cp"  placeholder="confirm your password">

  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>


{% endblock %}